import subprocess, sys, os, csv, random
os.chdir("/home/user")

print("=== 1: Install packages ===", flush=True)
for pkg in ["docx","openpyxl","matplotlib","numpy"]:
    mod = pkg.replace("-","_")
    try:
        __import__(mod)
        print(f"  {pkg}: OK", flush=True)
    except:
        subprocess.run([sys.executable,"-m","pip","install","-q",pkg], check=True)
        print(f"  {pkg}: installed", flush=True)

print("=== 2: Generate CSV ===", flush=True)
months = ["2026-01","2026-02","2026-03","2026-04","2026-05","2026-06"]
products = ["A","B","C","D","E"]
with open("sales_data.csv","w",newline="") as f:
    w = csv.writer(f)
    w.writerow(["Month","Product","Sales"])
    for m in months:
        for p in products:
            w.writerow([m, p, random.randint(10000, 500000)])
rows = len(open("sales_data.csv").readlines())
print(f"  Rows: {rows}", flush=True)

print("=== 3: Analyze ===", flush=True)
data = {}
with open("sales_data.csv") as f:
    for row in csv.DictReader(f):
        p = row["Product"]
        m = row["Month"]
        s = int(row["Sales"])
        if p not in data:
            data[p] = {"total":0, "months":{}, "first":0, "last":0}
        data[p]["total"] += s
        data[p]["months"][m] = s
        if m == months[0]:
            data[p]["first"] = s
        if m == months[-1]:
            data[p]["last"] = s

lines = ["# Sales Analysis Report\n"]
lines.append("\n| Product | Total | Avg | Growth |\n")
lines.append("|---------|-------|-----|--------|\n")
for p in sorted(data):
    d = data[p]
    g = (d["last"] - d["first"]) / d["first"] * 100
    lines.append(f"| {p} | {d['total']:,} | {d['total']//6:,} | {g:+.1f}% |\n")
lines.append(f"\n{rows-1} records analyzed.\n")
with open("analysis_report.md","w") as f:
    f.writelines(lines)
print(f"  Report: {os.path.getsize('analysis_report.md')}b", flush=True)

print("=== 4: Charts ===", flush=True)
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 5))
for p in products:
    vals = [data[p]["months"].get(m, data[p]["total"]//6) for m in months]
    ax.plot(months, vals, marker="o", label=p)
ax.legend()
ax.set_title("Monthly Sales Trend")
ax.tick_params(axis="x", rotation=45)
plt.tight_layout()
plt.savefig("sales_trend.png")
plt.close()

fig, ax = plt.subplots(figsize=(8, 5))
totals = [data[p]["total"] for p in products]
bars = ax.bar(products, totals)
for bar, v in zip(bars, totals):
    ax.text(bar.get_x()+bar.get_width()/2, v+5000, f"{v:,}", ha="center", fontsize=8)
ax.set_title("Total Sales by Product")
plt.tight_layout()
plt.savefig("sales_bar.png")
plt.close()
print(f"  Charts: trend={os.path.getsize('sales_trend.png')}b bar={os.path.getsize('sales_bar.png')}b", flush=True)

print("=== 5: Word Report ===", flush=True)
from docx import Document
doc = Document()
doc.add_heading("2026 H1 Sales Report", 0)
doc.add_paragraph("Generated by TokenFund AI Agent")
doc.add_heading("Data Overview", level=1)
doc.add_paragraph(f"Records: {rows-1} | Products: {len(products)} | Months: {len(months)}")
table = doc.add_table(rows=1, cols=4)
table.style = "Light Grid Accent 1"
for i, h in enumerate(["Product","Total Sales","Monthly Avg","Growth"]):
    table.rows[0].cells[i].text = h
for p in sorted(data):
    d = data[p]
    g = (d["last"] - d["first"]) / d["first"] * 100
    row = table.add_row()
    row.cells[0].text = p
    row.cells[1].text = f"{d['total']:,}"
    row.cells[2].text = f"{d['total']//6:,}"
    row.cells[3].text = f"{g:+.1f}%"
doc.add_heading("Charts", level=1)
doc.add_paragraph("Figure 1: Monthly sales trend (sales_trend.png)")
doc.add_paragraph("Figure 2: Total sales by product (sales_bar.png)")
doc.save("final_report.docx")
print(f"  Report: {os.path.getsize('final_report.docx')}b", flush=True)

print("=== 6: Verify ===", flush=True)
for fn in ["sales_data.csv","analysis_report.md","sales_trend.png","sales_bar.png","final_report.docx"]:
    sz = os.path.getsize(fn)
    print(f"  {fn}: {sz}b", flush=True)
print("OK ALL DONE", flush=True)
